### ISSUE TITLE
Multiple accounts, same email address

### ISSUE THREAD

**Issue by ediechit** [LeoneBacciu/django-email-verification#26]
Hi,

I'm not seeing this addressed elsewhere, so please point me in the right direction if it was discussed.

When creating 2 or more accounts with the same email address, I'm getting a 'MyModel.models.User.MultipleObjectsReturned: get() returned more than one User -- it returned 2!' error.

Though uncommon, it might not be that unreasonable for a website to allow multiple accounts on the same email address. The previous version of your app had no issue with that.

Is this something that could be tweaked to allow for such a case?

Thanks,
E.Z.

**Comment by LeoneBacciu** [comment]
Thank you for pointing this out.
It's my fault 😅, I removed this feature because I couldn't see a valid reason for it. But you are right, it isn't that unreasonable after all.
You can stick with `0.0.9` for now. In the next version this feature will be included as optional (you will be able to enable it in the `settings.py`).
Because of the way the token validation works the email will validate only the concerned user and not the others (with the same email). Does this make sense?

**Comment by LeoneBacciu** [comment]
I've added this feature in 877cb9d604a2b03c039299c113b9b067d656ed09!
You can build this in your own (`python3 setup.py sdist bdist_wheel`) or wait a few weeks for the next release to be published.
Thank you.
I will close this issue.

**Comment by ediechit** [comment]
Thanks, Leone. Great work
