### ISSUE TITLE
Error Invalid Token

### ISSUE THREAD

**Issue by manojsitapara** [LeoneBacciu/django-email-verification#30]
Thank you for making this package to make our life easier.

When I click on activation link which I received in confirmation email it give me following error

> Error Invalid Token

Following value set in settings.py

`EMAIL_TOKEN_LIFE = 259200`

This means token life should be 259200 seconds, right?

but when I click on activation email, it says that token is Invalid.

NOTE: I am using custom user model and specified it in settings.py 

`AUTH_USER_MODEL = 'account.user'`

**Comment by mdsherwood** [comment]
![image](https://user-images.githubusercontent.com/7293371/110478279-dc348a00-80ec-11eb-948d-acdd7b8478a3.png)

It's definitely the hash_string that being calculated differently

**Comment by millerthegorilla** [comment]
Are you using a class based view?   If so, did you call the super class form_valid function?
https://github.com/LeoneBacciu/django-email-verification#email-sending

**Comment by mdsherwood** [comment]
Hi I'm actually sending the email from the serializer as that's where I'm creating the User object as part of a Subscriber object creation by overriding create.

The problem is that the user I'm passing into send_mail is obtained like this:
user = UserSerializer.create(UserSerializer(), validated_data=user_data)
while the user that is being used to generate the token on verify is obtained like this:
user = get_user_model().objects.get(email=email)

I added a line to get the user the same way in my serializer and now it works :-)

Thanks for the feedback

**Comment by millerthegorilla** [comment]
Well, I now have the same problem.  It works ok using the console backend, but I get an invalid token using my now production server.  Gah.   its end of day for me now.  I shall have a look tomorrow, or the following day.

**Comment by LeoneBacciu** [comment]
Is this issue still occouring? Please check with the latest release [0.1.1rc0](https://pypi.org/project/django-email-verification/0.1.1rc0/).
